(defvar chatgpt-shell-streaming nil)
(defvar chatgpt-shell-model-version "gpt-4o")
(defvar chatgpt-shell-mode-map (make-sparse-keymap))
(defun chatgpt-shell-crop-context (&rest _) nil)
(defun chatgpt-shell-mode () nil)
(provide 'chatgpt-shell)
(load-file "contrib/aob-chatgpt.el")
(let* ((fake-edn "---FROM-CHATGPT-EDN---\n{:session-id \"test\" :clock \"2025\" :patterns ({:title \"Sample\" :summary \"Short\" :score 0.1})}\n---END-FROM-CHATGPT-EDN---")
       (text (concat "Response body\n" fake-edn)))
  (message "PARSED %S" (my-chatgpt-shell--extract-chatgpt-edn text)))
