(defun my-chatgpt-shell--insert-edn-summary (edn)
  (let ((inhibit-read-only t))
    (insert (propertize "Latest FROM-CHATGPT state" 'face 'bold) "\n")
    (when-let ((session (plist-get edn :session-id)))
      (insert (format "Session: %s\n" session)))
    (when-let ((clock (plist-get edn :clock)))
      (insert (format "Clock: %s\n" clock)))
    (when-let ((patterns (seq-filter #'identity (plist-get edn :patterns))))
      (insert "Patterns:\n")
      (dolist (pattern patterns)
        (let ((title (or (plist-get pattern :title)
                         (plist-get pattern :id)))
              (summary (plist-get pattern :summary))
              (score (plist-get pattern :score)))
          (insert (format "  • %s%s\n    %s\n"
                          (or title "")
                          (if (numberp score)
                              (format " (%.2f)" score)
                            "")
                          (my-chatgpt-shell--truncate summary 120))))))
    (when-let ((fruits (seq-filter #'identity (plist-get edn :fruits))))
      (insert "Fruits:\n")
      (dolist (fruit fruits)
        (let ((emoji (plist-get fruit :emoji))
              (name (or (plist-get fruit :fruit/id)
                        (plist-get fruit :id)))
              (score (plist-get fruit :score)))
          (insert (format "  • %s %s%s\n"
                          (or emoji "")
                          (or name "")
                          (if (numberp score)
                              (format " (%.2f)" score)
                            ""))))))
    (when-let ((paramitas (seq-filter #'identity (plist-get edn :paramitas))))
      (insert "Paramitas:\n")
      (dolist (param paramitas)
        (let ((orb (plist-get param :orb))
              (emoji (plist-get param :emoji))
              (name (or (plist-get param :paramita/id)
                        (plist-get param :id)))
              (score (plist-get param :score)))
          (insert (format "  • %s %s%s%s\n"
                          (or orb "")
                          (or emoji "")
                          (if name (format " %s" name) "")
                          (if (numberp score)
                              (format " (%.2f)" score)
                            ""))))))
    (when-let ((events (seq-filter #'identity (plist-get edn :events))))
      (insert "Events:\n")
      (dolist (evt events)
        (let ((actor (plist-get evt :actor))
              (text (or (plist-get evt :notes)
                        (plist-get evt :text)))
              (activity (plist-get evt :activity)))
          (insert (format "  • %s%s %s\n"
                          (if actor (format "%s " actor) "")
                          (if activity (format "[%s]" activity) "")
                          (or text "")))))
      (insert "\n"))))
